apiVersion: v1
kind: Service
metadata:
  name: mysql-db 
  labels:
    app: mysql-db
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    app: mysql-db
    release: {{ .Release.Name }}
