apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  # params:
  steps:
    - name: echo-goodbye
      image: ubuntu
      script: |
        #! /bin/bash
        echo "Goodbye, Tekton!"